FROM oraclelinux:7-slim AS development

RUN  yum -y install oracle-release-el7 oracle-nodejs-release-el7 && \
     yum-config-manager --disable ol7_developer_EPEL && \
     yum -y install oracle-instantclient19.3-basiclite nodejs curl bash make && \
     rm -rf /var/cache/yum

# Specify our working directory, this is in our container/in our image
WORKDIR /milan/src/app

# Copy the package*.json from host to container
COPY package*.json ./

# Here we install all the deps
RUN npm install -g npm@8.12.2 \
 && npm install -g ts-node \
 && npm install -g yarn \
 && npm install \
 && npm audit

# Bundle app source / copy all other files
COPY . .

# Build the app to the /dist folder
RUN npm run build

EXPOSE 3001

# # Run app
CMD [ "node", "dist/main" ]
