### Do not USE in production !!!
version: '3.14'

services:
  nestjs-poc-mysql:
    image: poc/nestjs-poc-mysql
    container_name: nestjs-poc-mysql
    build:
      context: ./
      dockerfile: Dockerfile.dev
      target: development
    # Mount our host Directory to the docker container
    # Mount app directory to the docker container milan/src/app
    # reflect file changes from host to container
    volumes:
      - ./:/milan/src/app
      - /milan/src/app/node_modules
    # Run in Debug Mode: npm run start:debug --> Don't forget to start your vscode debugger!
    # Run in dev Mode: npm run start:dev
    command: npm run start:dev
    depends_on:
      - mysql
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: 'mysql'
      DB_PORT: '3306'
      DB_USER: 'root'
      DB_PASS: 'root'
      DB_SERVICE_NAME: 'poc'
    ports:
      - 3001:3001

  nestjs-poc-oracle:
    image: poc/nestjs-poc-oracle
    container_name: nestjs-poc-oracle
    build:
      context: ./
      dockerfile: Dockerfile.dev
      target: development
    # Mount our host Directory to the docker container
    # Mount app directory to the docker container milan/src/app
    # reflect file changes from host to container
    volumes:
      - ./:/milan/src/app
      - /milan/src/app/node_modules
    # Run in Debug Mode: npm run start:debug --> Don't forget to start your vscode debugger!
    # Run in dev Mode: npm run start:dev
    command: npm run start:dev
    depends_on:
      - oracle
    environment:
      NODE_ENV: development
      PORT: 3002
      DB_HOST: 'oracle'
      DB_PORT: '1521'
      DB_USER: 'oracleuser'
      DB_PASS: 'oraclepwd'
      DB_SERVICE_NAME: 'XEPDB1'
    ports:
      - 3002:3002

  # sudo docker run -d -it --rm --name oracle-xe -p 1521:1521 -p 5500:5500 -e ORACLE_PWD=oraclepwd -v /home/ubuntu/oracle/oradata:/opt/oracle/oradata oracle/database:18.4.0-xe
  oracle:
    image: oracle/database:18.4.0-xe
    container_name: oracle
    volumes:
      - ../../../oracle/oradata:/opt/oracle/oradata
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      ORACLE_PWD: oraclepwd

  mysql:
    image: mysql:8
    # restart: always
    container_name: mysql
    volumes:
      - ../../../mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_TCP_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: poc
